const Hotellist=[
    {
        id:1,
        code:992581199996,
        percent:0.4,
        name:"Harikrushna Restaurant",
        location:"Kamrej, Surat",
        image:"/images/HarikrushnaKamrej/hk1.jpeg",
        image2:"/images/HarikrushnaKamrej/hk2.jpeg",
        image3:"/images/HarikrushnaKamrej/hk3.jpeg",
        image4:"/images/HarikrushnaKamrej/hk1.jpeg",
        image5:"/images/HarikrushnaKamrej/hk4.jpeg",
        image6:"/images/HarikrushnaKamrej/hk5.jpeg",
        image7:"/images/HarikrushnaKamrej/hk6.jpeg",
        image8:"/images/HarikrushnaKamrej/hk7.jpeg",
        discount:"10%",
        special:"",
        contact:"9925899996",
        menu:{
            Soup:{"Tomato Soup":120,"Veg Manchow Soup":130,"Veg Hot & Sour Soup":130,"Sweet Corn Soup":135,"Lemon & Corriander Soup":145},
            Chinese:{"Manchurian Dry":160,"Manchurian Gravy":160,"Veg Hakka Noodles":160,"Schezwan Fry Rice":160,"Veg Fry Rice":160,"Manchurian Rice":160,"Special Chinese Bhel":170,"Veg Crispy":180,"Paneer Chilli Dry":210,"Paneer Chilli Gravy":210},
            Other:{"Chole Bhature":150,"Cheese Chole Bhature":180,"Paneer Chole Bhature":180,"Extra Bhature":50},
            Kathiyawadi:{"Rajwadi Undhiyu":95,"Rajwadi Dhokali":95,"Sev Tameta":90,"Potato Shak":90,"Kathol Shak":90,"Lasaniya Sev Tameta":105,"Dal(Kathiyawadi)":40,"Bhaat":40,"Kadhi(Evening)":40,"Khichdi(Evening)":40,"Vegetable Khichdi(Evening)":90,"Masala Khichdi(Evening)":90,"Palak Khichdi(Evening)":90,"Dal Khichdi":100,"Dahi Tikhari":95,"Dahi":50,"Rotla(Bajri)":28,"Tawa Parantha":28,"Swami Roti":16,"Gud":20},
            Kaju:{"Kaju Curry":230,"Kaju Paneer":250,"Kaju Masala":240,"Kaju Handi":240,"Kaju Palak Masala":240,"Kaju Butter Masala":240,"Kaju Cheese Masala":250,"Kaju Lasaniya":250,"Special Harikrushna":250},
            KathiyawadiDesiDhamal:{"Kathiyawadi Special":135,"Sp. Cheese Lilidungdi Tameta":135,"Kajughatiya Shak":130,"Kaju Patra":130,"Lilva Patra":130,"Makai Tameta":100,"Liladana Lasan Shak":130,"Jira Aloo":100,"Desi Shak Dungli Bateta":105,"Lilidungli Gathiya Shak":105,"Bharela Ringal Ditiya Shak":105,"Lili Dungli Bateta":105,"Sev Methi Shak":105,"Lila Shakbhaji Mix":105},
            Vegetable:{"Chana Masala":160,"Veg Kadhai":170,"Mix Veg":170,"Veg Hariyali":180,"Veg Kolhapuri":180,"Veg Makhanwala":180,"Veg Diwani Handi":180,"Veg Angara":200,"Veg Jaipuri":180,"Veg Cheese Tawa":210,"Veg Tawa":180,"Veg Toofani":180,"Veg Handi":180},
            Paneer:{"Chana Paneer":185,"Matar Paneer":185,"Palak Paneer":190,"Paneer Kadhai":190,"Paneer Tikka Masala":190,"Paneer Chatpata":190,"Paneer Toofani":190,"Paneer Maharaja":190,"Paneer Butter Masala":190,"Paneer Angara":190,"Paneer Diwani Handi":190,"Paneer Bhuji":210,"Paneer Mushroom Masala":210,"Junglee Paneer":210,"Paneer Lasaniya":210,"Cheese Paneer Masala":210,"Cheese Butter Masala":210,"Mushroom Masala":210,"Paneer Masala":190,"Paneer Tawa Masala":190,"Paneer Pasanda":210},
            Dal:{"Dal Fry":130,"Dal Fry Tadka":150,"Dal Hariyali":150,"Dal Kolhapuri":150},
            Rice:{"Jira Rice":110,"Veg Pulav":150,"Veg Biryani":155,"Kaju Pulav":165,"Hyderabadi Biryani":160},
            TandooriEvening:{"Plain Tandoori Roti":35,"Butter Tandoori Roti":40,"Plain Tandoori Parantha":45,"Butter Tandoori Parantha":50,"Plain Kulcha":45,"Butter Kulcha":50,"Plain Tandoori Naan":50,"Butter Tandoori Naan":60,"Cheese Naan":95,"Cheese Garlic Naan":95}
        },
        rating:"New",
        openhr:11,
        openmin:0,
        closehr:22,
        closemin:30,
        direction:"https://goo.gl/maps/Gpbin39k2gYHNJmW9",
        cuisine:"Gujarati, Punjabi, Kathiyawadi, Chinese",
        type:"Fine dine",
        menulink:`https://drive.google.com/file/d/16F41f1Pq4XldeBYyLRh16hoj2CIW-s-e/view?usp=sharing`,
        costavg:"500 for 2 person"
    
    },
    {
        id:11,
        name:"Secret Kitchen",
        location:"Piplod, Surat",
        image:"/images/SecretKitchenPiplod/sk1.webp",
        image2:"/images/SecretKitchenPiplod/sk2.webp",
        image3:"/images/SecretKitchenPiplod/sk3.webp",
        image4:"/images/SecretKitchenPiplod/sk4.webp",
        image5:"/images/SecretKitchenPiplod/sk5.webp",
        image6:"/images/SecretKitchenPiplod/sk6.webp",
        image7:"/images/SecretKitchenPiplod/sk7.webp",
        image8:"/images/SecretKitchenPiplod/sk8.webp",
        discount:"10%",
        special:"",
        contact:"9825729729",
        discount:"10%",
        menu:{
            TheHotBar:{"Corn Fondue Soup":209,"Lehsuni Rasam":219,"A-B-C Soup":229,"Classic Tomato Soup":199,"Chinese Hot Pot":209,"Burmese Khow Suey Soup":229,"Lemon Coriander Soup":209,"Tomato Cheese Broccoli":239},
            TheFirstPlate:{"The Gup Shup Platter":219,"Tandoori Paneer Vol Au Vent":359,"Taquito Kachori":389,"Kutchi Palak Chat":339,"Mango Dahi Puri":319,"Bhujodi Paneer":369,"Stuff Fried Pasta #TSKFied":399,"Schezwan Corn Manchurian":339,"The Seven Cheese Tikki":419,"Corn Patty W Berry Salsa":399,"Nawabi Paneer Tikka":399,"Firangi Crispy Veg":379,"Corn & Cottage Cheese Tacos":349,"#TSKFied Nachos":339,"The Smokey Pizza":379,"Pink Pasta":389,"Pesto Paneer Pastry":339,"Paneer Sheekh Kebab":369,"Hara Bhara Kebab":359,"Stuffed Mushroom":399,"Bhav Nagari Chilli Cheese":419,"Dahi Kebab":399},
            TheSharingPlate:{"Thai Sizzler":599,"Sizzling Corn Risotto":539,"The Jalsa Platter":499},
            TheMainPlate:{"Cheese Ball Curry":479,"Punjabi Tawa Undhiyu":479,"Mughali Paneer":439,"Amritsari Paneer(360gms)":419,"Lucknowi Paneer Butter Masala(350gms)":439,"Makhana Makhanwala(350gms)":459,"Malai Kofta":459,"Green Cheese Butter Masala #TSKFied":469,"Patiyala Tawa Paneer #TSkFied":419,"Malabar Subz":449,"Mangalorean Corn":429,"Lucknowi Methi Mutter Malai":439,"Lasaniya Mushroom":449,"Bhoona Bhurji":409,"Cook Your Own Curry":449},
            TheComfortPlate:{"Khichdi Sizzlers":419,"Berry Kashmiri Pulav":439,"Jeera Onion Rice":259,"Sizzling Biryani":359,"Dal Tadka":289,"Dal Khichdi":349,"Dal Makhani":399,"Green Peas Pulao":269,"Subz Pulao":269,"Ghee Rice":269,"Matka Biryani":399,"Hyderabad Dum Biryani":419,"Dal Fry":279},
            ShakenStirred:{"Saffron Martini":249,"The Red Wine":349,"Marshmellowtini":289,"Roasted Pineapple Tulsi Cooler":249,"Bellini Blast":289,"Vodkatini":219,"The Monster Munch":269,"Blue Berry Mojito":199,"Fusion Margarita":249,"Live Ice Tea":249,"Guava Mint Masala":219,"Kiwi Basil":199,"Plancolada":219,"Fresh Lime Soda":159,"Mango Smoothies":249},
            TheWorldSizzler:{"Italian Sizzler":589,"Hong Kong Sizzler":589,"Mexican Sizzler":589},
            TheWorldPlate:{"Tandoori Platter":499,"The Arabic Platter":589,"NYC Platter":449,"Hakka Noodle":349,"Chilly Garlic Noodle":399,"Chilli Paneer":419,"Honey Chilli Potato":369,"Mushroom Black Papper":419,"Exotic Vegetable in Butter Garlic Sauce":419,"Burnt Garlic Rice":399,"Triple Schezwan Rice":399},
            Pasta:{"Pesto Pasta":389,"Alfredo Pasta":389,"Arrabiata Pasta":389,"Aglio E Olio Sphagetti":379},
            BreadBar:{"Tandoori Roti Butter":69,"Tandoori Roti Plain":69,"Multi Grain Roti":109,"Garlic Onion Naan":139,"Lehsuni Butter Kulcha":139,"Tandoori Naan Butter":109,"Tandoori Naan Plain":109,"Reshmi Paratha Aka Puff Paratha":219,"Kashmiri Cheese Naan":179,"Cheese Chilly Naan":159,"Pesto Kulcha":159},
            SweetPlate:{"Mango Cheese Cake":459,"Peanut Halwa With Rabdi":479,"Sizzling Gulab Jamun with Brownie":439,"Soften Gulab Jamun(3pcs)":159,"Ice Cream":159},
            TheDessertBar:{"Chef Aanal's Autograph":559},
            Other:{"Green Salad":159,"Roasted Papad":79,"Fried Papad":79,"Masala Papad(2pcs)":159,"Masala Chaas":129,"Curd":109,"Lassi":229,"French Fries":159,"Garlic Bread":219,"Cheese Garlic Bread(4pcs)":249,"Tangy Pasta Salad":249}
        },
        rating:"New",
        openhr:12,
        openmin:0,
        closehr:23,
        closemin:0,
        direction:"https://goo.gl/maps/UkVrAy3aj1cEPHn38",
        cuisine:"North Indian ,Beverages, Desserts",
        type:"Multicuisine",
        menulink:"https://drive.google.com/file/d/1ziAK8cj01GWxj57VhCpK2B1sW0c_NK5I/view?usp=sharing",
        costavg:"700 for 2 person"
    },
    {
        id:9,
        name:"King's Corner Pal",
        location:"Pal, Surat",
        image:"/images/KingsCornerPal/kc1.jpeg",
        image2:"/images/KingsCornerPal/kc2.jpeg",
        image3:"/images/KingsCornerPal/kc3.jpeg",
        image4:"/images/KingsCornerPal/kc4.jpeg",
        image5:"/images/KingsCornerPal/kc5.jpeg",
        image6:"/images/KingsCornerPal/kc6.jpeg",
        image7:"/images/KingsCornerPal/kc7.jpeg",
        image8:"/images/KingsCornerPal/kc8.jpeg",
        discount:"10%",
        special:"",
        contact:"7575061500",
        menu:{
            Soup:{"Cream N Tomato":140,"Hot & Sour Soup":140,"Veg Manchow Soup":140,"Palak ka Sorba":150,"Tom Yum Soup":180,"Burmese Soup":180,"Mexican Soup":150,"Almond Brocolli Soup":160,"Spicy Cheese Soup":160,"Thai Corriander Soup":150},
            Rolls:{"Spring Roll":230,"Paneer Schezwan Roll":260,"Cheese Cigar Roll":280,"Dragon Roll":280},
            Starter:{"Paneer Tikka Dry":290,"Paneer Sholay Kabab":320,"Paneer Kakori Kabab":320,"Paneer Pahadi Kabab":320,"Makhmali Kabab":250,"Pathani Kabab":250,"Reshmi Tandoori Balls":250,"Corn Seekh Kabab":270,"Hara Bhara Kabab":250,"Stuff Mushroom Tikka":270,"Tandoori Platter":450,"Veg Manchurian":180,"Veg 65":250,"Veg Lollypop":270,"Veg Green Crispy":270,"Dragon Potato":270,"Honey Chilli Potato":270,"Sunheri Potato":270,"Paneer Mongolian":280,"Panner Hot Pan":280,"Paneer Melody":280,"Paneer Chilli":260,"Stir Fru Veggie Paneer":260,"Pesto Potato":260,"Thai Paneer Chilli":280,"Basil Paneer Chilli":280},
            SoyaChap:{"Masala Chaap":280,"Afghani Chaap":280,"Chatpata Chaap":280,"Cheesy Malai Chaap":300},
            Salad:{"Green Salad":120,"Russian Salad":180,"Greek Salad":200},
            Papad:{"Roasted Papad":30,"Fried Papad":40,"Masala Papad":60,"Dollar Masala Papad":80},
            Sandwich:{"French Fries":130,"Veg Sandwich":100,"Veg Cheese Sandwich":120,"Grill Sandwich":200,"Toast Sandwich":150,"Garlic Bread":200,"Cheese Chilli Toast":200},
            Pizza:{"Cheesy Margherita Pizza":220,"No Mercy Pizza":220,"Green Paradise Pizza":230,"Mushroom Chilli Pizza":230,"La Tomatino Pizza":220,"Italian Pizza":240,"Barbeque Paneer Pizza":250,"Hara Bhara Firangi Pizza":230},
            Pasta:{"Pasta in Red Sauce":300,"Pasta in White Sauce":300,"Italian Pasta":320,"Four Maggi Pasta":350},
            BakedDishes:{"Italian Swiss Roll":380,"Lasagne Supreme":380,"Lasagne Premium":350},
            Noodles:{"Hakka Noodles":260,"Schezwan Noodles":270,"Ching Chong Noodles":280,"Pad Thai Noodles":300},
            Rice:{"Veg Fried Rice":250,"Veg Schezwan Rice":260,"Chinese Bhel":260,"Veg Triple Rice":280,"Mexican Rice":270,"Thai Rice":270,"Lemon Rice":250,"Mix Herbs Rice":250,"Jeera Rice":200,"Veg Pulav":250,"Handi Biryani":260,"Hyderabadi Biryani":260,"Paneer Biryani":270,"Kabuli Biryani":270,"Dum Biryani":270,"Masala Khichdi":220,"Palak Garlic Khichdi":230,"King's Corner Special Biryani":280},
            Dosa:{"Sada Dosa":80,"Masala Dosa":150,"Nylon Sada Dosa":100,"Garlic Chilli Nylon":130,"Cheese Nylon":140,"Green Cheese Nylon":140,"Onion Nylon":130,"Jeera Nylon":130,"Chilli Oregano Nylon":130,"Mysore Masala Dosa":170,"Palak Paneer Dosa":220,"Cheese Sada Dosa":120,"Cheese Palak Dosa":240,"Gotala Dosa(New)":270,"Paneer Chilli Dosa":270,"Paneer Surma Dosa":270,"Paneer Cheese Mysore Dosa":270,"Jini Dosa":270,"Dilkhush Dosa":230,"Maggi Cheese Dosa":250,"Banglore Spring Dosa":230,"Chinese Dosa":230},
            Punjabi:{"Veg Kolhapuri":250,"Veg Makhanwala":250,"Veg Jaipuri":240,"Veg Kadhai":250,"Veg Handi":250,"Veg Tava":250,"Veg Khima Masala":250,"Veg Angara":270,"Veg Hariyali":250,"Veg Mughlai":250,"Veg Khajana":260,"Harabhara Kabab Masala":260,"Navratan Korma":260,"French Ravioli":290,"Veg Mili-Juli":290},
            Kofta:{"Veg Kofta":250,"Malai Kofta":260,"Lajawab Kofta":280,"Paneer Kofta":280,"Nargis Kofta":250,"Veg Ghustafa":270},
            KajuSpecial:{"Kaju Curry":320,"Kaju Crackly":320,"Corn Kaju Palak":320,"Khoya Kaju":320},
            Paneer:{"Paneer Palak":270,"Paneer Tikka":280,"Paneer Butter Masala":280,"Paneer Toofani":280,"Paneer Handi":290,"Paneer Kadhai":290,"Paneer Tawa":290,"Paneer Chatpata":290,"Paneer Bhurji":270,"Paneer Pasanda":290,"Paneer Mushroom Masala":290,"Paneer Patiala":290,"Paneer Angara":300,"Paneer Kaju Masala":320,"Paneer Hyedarabadi":290,"Paneer Jwala":290,"Paneer Mirch Masala":290,"Paneer Pahadi":290,"Paneer Matka":290,"Paneer Shehzadi":290,"Cheese Begum Bahar":320,"Paneer Sabnam":320,"Paneer Mughlai":290,"Paneer Kashba":300},
            Raita:{"Plain Curd":80,"Mix Veg Raita":120,"Pineapple Raita":140,"Bundi Raita":130,"Lassi":100,"Butter Milk":50},
            Roti:{"Plain Roti":35,"Butter Roti":40,"Missi Roti":80,"Butter Lachha Parantha":100,"Butter Reshmi Parantha":100,"Butter Naan":100,"Butter Kulcha":100,"Cheese garlic Naan":140,"Aloo Parantha":130,"Stuff Parantha":130,"Chura Parantha":100,"Pudina Parantha":100},
            Dal:{"Dal Fry":200,"Dal Tadka":220,"Dal Palak Tadka":230,"Dal Multani":230,"Kadhi Punjabi":220,"Kadhi Gujarati":220}
        },
        rating:"New",
        openhr:11,
        openmin:0,
        closehr:23,
        closemin:0,
        direction:"https://goo.gl/maps/6VQ4oLckmW74WSEB8",
        cuisine:"North & South Indian, Punjabi, Chinese, Beverages",
        type:"Multicuisine",
        menulink:"https://drive.google.com/file/d/1mZojY0p-v0_jIs3v6Yvmihn_6OjfLUYN/view?usp=sharing",
        costavg:"500 for 2 person"
    },
    {
        id:10,
        name:"Sizzling Bite",
        location:"Piplod, Surat",
        image:"/images/SizzlingBitePiplod/sb1.jpeg",
        image2:"/images/SizzlingBitePiplod/sb2.jpeg",
        image3:"/images/SizzlingBitePiplod/sb3.jpeg",
        image4:"/images/SizzlingBitePiplod/sb4.jpeg",
        image5:"/images/SizzlingBitePiplod/sb5.jpeg",
        image6:"/images/SizzlingBitePiplod/sb6.jpeg",
        image7:"/images/SizzlingBitePiplod/sb7.jpeg",
        image8:"/images/SizzlingBitePiplod/sb8.jpeg",
        discount:"10%",
        special:"",
        contact:"9662400129",
        menu:{
            Mojitos:{"Mint":199,"Green Apple":199,"Cranberry":199,"Orange":199,"Watermelon":199},
            IcedTea:{"Lemon":177,"Peach":177,"Cranberry":177},
            Mocktails:{"Nuclear Cosmopolitan":209,"Virgin Pinacolada":219,"Death Sip":239,"Bulls Eye":399,"G spot":245,"Carribean Blizzard":249,"Vh1 Night Stand":247},
            Shakes:{"Kit Kat Shake":269,"Ohh Reo Shake":265,"Caramello Brownie Shake":309,"Rocher Shake":339,"Biscoff Shake":319,"Pie Pie Shake":309},
            Beverages:{"Fresh Lime Soda Sweet":75,"Fresh Lime Soda Salted":75,"Butter Milk Plain":85,"Butter Milk Masala":85,"Lassi Sweet":119,"Lassi Salted":119},
            Soup:{"Manchow":159,"Smoked Tomato Basil":159,"Veg Sweet Corn":162,"Brocolli Almond":181,"Pesto Corn Broth":199,"Veg Lemon Pepper Coriander":179,"Tom Yem":209,"Cream of Soup(Garlic)":189,"Cream of Soup(Mushroom)":189,"Cream of Soup(Veg&Cheese)":189,"Cream of Soup(Fried Onion)":189,"Burmese Khousuey":249,"Sangletang":199,"Veg Lemon Grass":219,"Smoked Veg Garlic":195},
            GarlicBreads:{"Garlic Bread With Cheese":169,"Chilli Cheese Garlic Bread":179,"Exotic Cheese Garlic Bread":192,"Feta Cheese Garlic Bread":209,"Cheddar Cheese Garlic Bread":219,"Cheese Bomb Garlic Bread":235,"Pesto Cheese Garlic Bread":229,"Schezwan Cheese Garlic Bread":209},
            Starter:{"Manchurian Veg":269,"Manchurian Schezwan":279,"Veg Spring Roll":289,"Lollipop Sticks":299,"Dragon Potato":279,"Potato Basil Chilli":279,"Mushroom Basil Chilli":297,"Cottage Cheese Basil Chilli":319,"Crispy Veg":299,"Potato Korean Chilli":289,"Mushroom Korean Chilli":307,"Cottage Cheese Korean Chilli":329,"Coriander Chilli Cottage Cheese":305,"Baby Corn Schezwan":279,"Mushroom Schezwan":299,"Cottage Cheese Schezwan":309,"Mushroom Chilli":285,"Cottage Cheese Chilli":299,"Mushroom Chilli Lemon Grass":305,"Cottage Cheese Chilli Lemon Grass":329,"Mushroom Peri Peri":299,"Cottage Cheese Peri Peri":317,"Mushroom Thai Cajun":319,"Cottage Cheese Thai Cajun":339,"Indonesian Baby Corn":297,"Indonesian Mushroom":319,"Indonesian Cottage Cheese":329,"Crisp Schezwan Corn":275},
            Fries:{"Classic Fries":159,"Spicy BBQ Fries":175,"Peri Peri Fries":179,"Cheddar Fries":185,"Loadede Italian Fries":209},
            Mexican:{"Classic Nachos":249,"Nachos Exotica":329,"El Rancho Loaded Nachos":359,"Cheese Tortilla":275,"Corn Cheese Balls":259,"Classic Bruschetta":269,"Supreme Bruschetta":299,"Quesdilla":349,"Enchiladas":369,"Pesto Paneer":329,"Bean Tacos":299,"Paneer Tacos":319,"Peri Peri Paneer Skewers":329,"Burrito Bowl":369},
            Lebanese:{"Falafel Bullets":259,"Crisp garlic Pita with Hummus":269,"Za'atar Pita with Chilled Lebnah":285,"Za'atar Pita Cheese with Hummus & Lebnah":299,"Crisp Garlic Pita with Tzatziki Dip":269,"Marrakeh Falafal":267,"Mexican Falafal":257,"Peri Peir Falafal":271,"Turkish Falafal":269},
            Rice:{"Cheese Pepper Rice":295,"Spiced Mexican Chilli Bean Rice":305,"Jalapeno Cilantro Rice":299,"Mediterranean Rice":307},
            BakedDish:{"Tomatina Lasagne":429,"Corn & Spinach Lasgna":429,"Exotic Lasagna":439,"Mac & Cheese Pineapple":429},
            PizzaClassic:{"Cheesy Bite Small":170,"Cheesy Bite Medium":310,"Cheesy Bite Large":420,"Marvellous Margherita Small":170,"Marvellous Margherita Medium":310,"Marvellous Margherita Large":420,"Veggie Veggie Small":170,"Veggie Veggie Medium":310,"Veggie Veggie Large":420,"Veggie Delight Small":210,"Veggie Delight Medium":420,"Veggie Delight Large":540,"Garden Heat Small":210,"Garden Heat Medium":420,"Garden Heat Large":540,"Spicy Paneer Small":210,"Spicy Paneer Medium":420,"Spicy Paneer Large":540,"Triple Delight Small":210,"Triple Delight Medium":420,"Triple Delight Large":540},
            PizzaNation:{"Tandoori Paneer Small":275,"Tandoori Paneer Medium":540,"Tandoori Paneer Large":655,"Classic Veggie Small":275,"Classic Veggie Medium":540,"Classic Veggie Large":655,"Schezwan Delight Small":275,"Schezwan Delight Medium":540,"Schezwan Delight Large":655,"Veggie Explosion Small":275,"Veggie Explosion Medium":540,"Veggie Explosion Large":655,"Ultimate Veg Small":275,"Ultimate Veg Medium":540,"Ultimate Veg Large":655,"Paneer Makhani Small":275,"Paneer Makhani Medium":540,"Paneer Makhani Large":655,"Veg Paradiso Small":275,"Veg Paradiso Medium":540,"Veg Paradiso Large":655,"Farm Ville Small":275,"Farm Ville Medium":540,"Farm Ville Large":655,"Kadai Paneer Small":275,"Kadai Paneer Medium":540,"Kadai Paneer Large":655},
            PizzaGlobe:{"Texas BBQ Small":295,"Texas BBQ Medium":595,"Texas BBQ Large":710,"Moroccan Madness Small":295,"Moroccan Madness Medium":595,"Moroccan Madness Large":710,"African Peri Peri Small":295,"African Peri Peri Medium":595,"African Peri Peri Large":710,"Mexican Roulette Small":295,"Mexican Roulette Medium":595,"Mexican Roulette Large":710,"Carribean Jerk Small":295,"Carribean Jerk Medium":595,"Carribean Jerk Large":710,"Spanish Pesto Small":295,"Spanish Pesto Medium":595,"Spanish Pesto Large":710,"Thai Dynasty Small":295,"Thai Dynasty Medium":595,"Thai Dynasty Large":710,"Garlickey Veg Small":295,"Garlickey Veg Medium":595,"Garlickey Veg Large":710,"Pesto Veggie Small":295,"Pesto Veggie Medium":595,"Pesto Veggie Large":710},
            PizzaSupreme:{"Bell Exotic Small":310,"Bell Exotic Medium":610,"Bell Exotic Large":730,"Supreme Veggie Small":310,"Supreme Veggie Medium":610,"Supreme Veggie Large":730,"Paneer Exotica Small":310,"Paneer Exotica Medium":610,"Paneer Exotica Large":730,"7 Chinese Treasure Small":310,"7 Chinese Treasure Medium":610,"7 Chinese Treasure Large":730},
            PizzaItaliano:{"Olive Olive":679,"Milano":679,"Marinara":679,"Sicily":679,"Mediterranean":679},
            Pasta:{"Aglio E Oile":330,"Sizzling Arabiatta":355,"Sizzling Alfredo":365,"Italian Pasta":375,"Pink Panther":377,"Pesto Paradise":389,"Pasta Del Porto":399,"Al Rigga":399,"Spaghetti Al Basilica":409,"Sphagetti E Olio":407},
            Sizzler:{"Exotica Sizzler":619,"Neopolitana Sizzler":619,"Chinese Sizzler":619,"Spicy Tangy Pepper Sizzler":619,"Fusion Sizzler":619,"Pan Pcific Sizzler":619,"Paneer Tikka Sizzler":619,"Thai Sizzler":619,"Peri Peri Sizzler":619,"Mexican Burrito Sizzler":619,"Paneer Shaslik Steak Sizzler":619,"Sphagetti Pesto Sizzler":619,"Oriental Masala Sizzler":619,"Romanian Cheese Sizzler":619},
            RiceNoodle:{"Fried Rice":239,"Schezwan Rice":269,"Schezwan Noodles":269,"Chilli Garlic Rice":269,"Chilli Garlic Noodles":269,"Chilli Basil Rice":279,"Thai Chilli Rice":293,"Korean Rice":285,"Peri Peri Rice":279,"Peri Peri Noodles":279,"Indonesian Rice":289,"Indonesian Noodles":289,"Hakka Noodles":239,"Exotic Noodles":281},
            Desserts:{"Sizzling Brownie":249,"Dark Cherry Brownie":269,"Biscoff Brownie":269},
            Papad:{"Roasted Papad":30,"Masala Papad":60,"Masala Cheese Papad":70}
        },
        rating:"New",
        openhr:11,
        openmin:0,
        closehr:23,
        closemin:0,
        direction:"https://goo.gl/maps/ExQdvfzt92XAptEU9",
        cuisine:"Mexican, Italian, Chinese, Beverages",
        type:"Cafe, Pizza",
        menulink:"https://drive.google.com/file/d/1AqNWs9FJweIhxEf6jlYiRzvXAkvcT3Bd/view?usp=sharing",
        costavg:"500 for 2 person"
    },
    {
        id:2,
        code:905401101536,
        name:"The Lion King",
        location:"Kashi Plaza, Kamrej",
        image:"/images/LionKingKamrej/lk3.jpeg",
        image2:"/images/LionKingKamrej/lk2.jpeg",
        image3:"/images/LionKingKamrej/lk1.jpeg",
        image4:"/images/LionKingKamrej/lk4.jpeg",
        image5:"/images/LionKingKamrej/lk5.jpeg",
        image6:"/images/LionKingKamrej/lk6.jpeg",
        image7:"/images/LionKingKamrej/lk7.jpeg",
        image8:"/images/LionKingKamrej/lk8.jpeg",
        discount:"10%",
        special:"",
        contact:"9054001536",
        menu:{
            Soup:{"Veg Sweet Corn":90,"Lemon Corriander":90,"Hot & Shower":100,"Manchow":110,"Tomato":90,"Cream of Mushroom":120,"Brokly(Mix)":110,"Brant Garlic":100},
            Sizzler:{"Veg Grilled":280,"Veg Indian Coaties":320,"Chilli Paneer":300,"Mix Veg":320},
            Chinese:{"Veg Noodle":130,"Veg Hakka Noodles":130,"Chilli Garlic Noodles":140,"Veg Schezwan Noodles":140,"Honey Chilli Potato":160,"Pen Fries Noodles":140,"Spring Roll":160,"Dragon Roll":170,"Veg Kothe":150,"Veg Manchurian":140,"Crispy Corn":150,"Veg Crispy":180,"Paneer Chilli":220,"Paneer 65":230,"Paneer Nuggets":250,"Paneer Crispy":220,"American Chopsy":180,"Cheese Ball":220,"Veg Fried Rice":130,"Manchurian Fried Rice":140,"Schezwan Fried Rice":140,"Triple Schezwan Fried Rice":200,"Veg All Mix":180,"Pasta Red Sauce":140,"Pasta White Sauce":180},
            TandoorKeAngaare:{"Veg Dahi Kabab(8pcs)":150,"Veg Harabhara Kabab(8pcs)":140,"Veg Sik Kabab(8pcs)":200,"Paneer Tikka":230,"Paneer Achari Tikka":240,"Paneer Lahori Tikka":260,"Paneer Lahsuni Tikka":240,"Paneer Hariyali Tikka":250,"Paneer Pahadi Tikka":250,"Paneer Malai Tikka":260,"Mushroom Tikka":260,"Babycorn Tikka":220,"Aloo Pahadi Tikka":180,"Fancy Tandoori Platter":400},
            Raita:{"Veg Raita":70,"Boondi Raita":80,"Pineapple Raita":100,"Fruit Raita":120},
            KajuSpecial:{"Kaju Curry":240,"Kaju Masala":240,"Kaju Paneer":260,"Kaju Khoya":240,"Kaju Lasanya":240},
            KoftaKamal:{"Veg Kofta":180,"Angoori Kofta":180,"Nargis Kofta":180,"Malai Kofta White":200,"Malai Kofta Yellow":200,"Paneer Kofta":180},
            Punjabi:{"Sev Tomato":120,"Mix Veg":160,"Veg Handi":160,"Veg Kolhapuri":180,"Jeera Aloo Methi":120,"Jeera Aloo Mutter":120,"Jeera Aloo Gobi":120,"Bhindi Masala":140,"Bhindi Jodhpuri":140,"Corn Tomato Masala":150,"Corn Palak":170,"Punjabi Chole":130,"Aloo Chole":120,"Chole Paneer":180,"Veg Hyderabadi":150,"Diwani Handi":180},
            Paneer:{"Mutter Paneer":170,"Paneer Masala":170,"Palak Paneer":170,"Paneer Kadhai":200,"Paneer Lavabdar":220,"Paneer Handi":240,"Paneer Punjabi":200,"Paneer Chatpata":220,"Paneer Kolhapuri":210,"Paneer Butter Masala":250,"Shahi Paneer":260,"Paneer Lahsuniya":230,"Paneer Tikka Masala":260,"Paneer Lahori Tikka Masala":260,"Paneer Angara":260,"Paneer Toofani":250,"Paneer Dhaba":260,"Paneer Kurchan":280,"Paneer Maratha":260,"Paneer Patiyala":280},
            Rice:{"Plain Rice":100,"Jeera Rice":120,"Masala Rice":120,"Veg Pulav":140,"Kashmiri Pulav":160,"Tava Pulav":130,"Veg Biryani":140,"Veg Matka Biryani":150,"Hydrabadi Biryani":150},
            Dal:{"Dal Fry":120,"Dal Tadka":130,"Dal Makhani":140,"Dal Lahsaniya":130,"Dal Palak":120},
            Bread:{"Plain Roti":10,"Butter Roti":15,"Plain Nan":30,"Butter Nan":40,"Messi Roti":40,"Lachcha Parantha":40,"Garlic Nan":50,"Stuffed Kulcha & Parantha":60,"Aloo Parantha":60,"Onion Parantha":50,"Mix Veg Parantha":50,"Plain Parantha":50,"Cheese Nan":70,"Cheese Garlic Nan":80,"Kashmiri Nan":80,"Bread Basket(6 Type of Tandoori Roti)":160},
            Thali:{"Punjabi Thali(1 Paneer Sabji, 1 Veg Sabji, 4 Butter Roti, Dal, Rice, Papad, Salad, Raita)":150},
            Other:{"Veg Fancy Cutlet":130,"French Fry":100,"Corn Chat":100,"Chole Bhature":100,"Chole Kulche":100}
        },
        rating:"New",
        openhr:11,
        openmin:0,
        closehr:23,
        closemin:30,
        direction:"https://goo.gl/maps/14dvUWvt7jJcNFX58",
        cuisine:"Gujarati, Punjabi, Kathiyawadi, Chinese",
        type:"Fine dine",
        menulink:"https://drive.google.com/file/d/10LTfiVv08pFMDRVlPfP7n9l1k9r5Fh82/view?usp=sharing",
        costavg:"500 for 2 person"
    },
    {
        id:3,
        code:812871529924,
        name:"Jail Chai Bar Cafe",
        location:"Sarthana, Surat",
        image:"/images/JailChaiBarSarthana/jcb1.jpeg",
        image2:"/images/JailChaiBarSarthana/jcb2.jpeg",
        image3:"/images/JailChaiBarSarthana/jcb3.jpeg",
        image4:"/images/JailChaiBarSarthana/jcb4.jpeg",
        image5:"/images/JailChaiBarSarthana/jcb5.jpeg",
        image6:"/images/JailChaiBarSarthana/jcb6.jpeg",
        image7:"/images/JailChaiBarSarthana/jcb7.jpeg",
        image8:"/images/JailChaiBarSarthana/jcb8.jpeg",
        discount:"10%",
        special:"",
        contact:"8128729924",
        menu:{
            Tea:{"Plain Tea":30,"Masala Tea":40,"Ginger Tea":40,"Elaichi Tea":40,"Chocolate Tea":50,"Mix Masala Tea":50,"Lemon Tea":60,"Classic Tulsi Tea":60,"Ginger Green Tea":60,"Masala Green Tea":60,"Lemon Iced Tea":120,"Mint Iced Tea":120,"Strawberry Iced Tea":120,"Green Apple Iced Tea":120,"Peach Iced Tea":120},
            Coffee:{"Black Coffee":40,"Hot Coffee":60,"Dark Hot Coffee":80,"Hot Chocolate Coffee":80,"Brownie Hot Coffee":110,"Cold Coffee":140,"Dark Cold Coffee":160,"Oreo Cold Coffee":180,"Chocolate Cold Coffee":180,"Hazelnut Cold Coffee":200,"Caragmel Cold Coffee":200,"Irish Cold Coffee":200,"Brownie Cold Coffee":220,"Espresso Tonic":180,"Classic Coldbrew Tonic":200,"Espresso":100,"Blueberry Tonic":250},
            Cocktails:{"Sex on the Beach":150,"Cosmopolitan":150,"Maragrita":150,"Gin Cherry Sour":150,"The New Old Fashioned":150,"Whiskey Sour":150},
            Shakes:{"Vanilla Shake":170,"Blueberry Shake":180,"Oreo Shake":200,"Bubble Gum Shake":180,"Strawberry Shake":180,"Kitkat Shake":200,"Caramel Shake":200,"Chocolate Shake":190,"Mango Shake":180,"Choco Irish Shake":200," Mix Berry Shake":220,"Choco Brownie Shake":240,"Oreo Brownie Shake Shake":240,"Kitkat Brownie Shake":240,"Pina Colada Shake":180,"Kiwi Shake":190,"Blackcurrent Shake":190,"Blackcurrent X Shake":210,"Strawberry X Shake":210,"Anjeer Shake":210},
            Mocktails:{"Mint Blast":150,"Blue Heaven":150,"Fresh Lemon":150,"Green Apple Mojito":150,"Strawberry":150,"Bubble Gum Temptation":150,"Summer Delight Watermelon":150,"Spicy Mango":150,"Spicy Lemon":150,"Peach":150,"Pan Mojito":150,"Beer":150,"Kala Khata":150,"Chilli Guava":150},
            Maggi:{"Masala Maggie":80,"Veg Masala Maggie":100,"Double Masala Maggie":100,"Veg Double Masala Maggie":120,"Cheese Corn Maggie":140,"Veg Mayo Maggie":120,"Veg Butter Garlic Maggie":120,"Chilli Cheese Maggie":160,"Veg Paneer Maggie":130,"Veg Cheese Corn Maggie":150,"Garlic Cheese Maggie":150,"Tandoori Maggie":170,"Schezwan Maggie":140,"Punjabi Tadka Maggie":170,"Tandoori Cheese Maggie":190,"Cheese Blast Maggie":190,"Cheese Masala Maggie":130},
            Sandwich:{"Masala Club Sandwich":180,"Veg Cheese Club Sandwich":200,"Classic Club Sandwich":220,"Cheese Paneer Club Sandwich":240,"Pizza Cheese Sandwich":250,"Jail Special Sandwich":280,"Chocolate Kachha Sandwich":110,"Chocolate Grilled Sandwich":120,"Oreo Sandwich":160,"Kitkat Sandwich":160,"Choco Brownie Sandwich":180,"Chocolate Club Sandwich":200,"Pineapple Sandwich":150,"Bombay Kachha Sandwich":100,"Veg Mayo Corn Sandwich":130,"Masala Cheese Sandwich":140,"Veg Cheese Sandwich":150,"Cheese Corn Sandwich":160,"Paneer Masala Sandwich":160,"Chill Cheese Sandwich":160,"Chill Paneer Sandwich":160,"Cheese Blast Sandwich":180,"Paneer Loaded Sandwich":180,"Veg Cheese Corn Sandwich":160,"Tandoori Sandwich":160,"Chill Cheese Corn Sandwich":170,"Paneer Makhani Sandwich":160,"Paneer Pizza Sandwich":180,"Bread Butter":50},
            Burger:{"Veg Burger":100,"Classich Cheese Burger":130,"Chilli Cheese Burger":160,"Mexican Burger":160,"Tandoori Paneer Burger":180,"Cheese Blast Burger":200},
            Pizza:{"Mergherita Pizza":220,"Cheese Corn Pizza":270,"Kadai Paneer Pizza":300,"Paneer & Onion Pizza":280,"Tandoori Paneer Pizza":300,"Fresh Farm Pizza":300,"Jail Special Pizza":370,"Palak Paneer Pizza":290,"OTC Pizza":250,"Extra Cheese Burst":110,"Basket Pizza-5pcs":200,"Fresh Farm(No Cheese)":230},
            Pasta:{"White Sauce Pasta":240,"Red Sauce Pasta":200,"Tandoori Pasta":260,"Mac and Cheese Pasta":290},
            SweetCorns:{"Butter Corn":100,"Veg Corn":110,"Butter Cheese Corn":130,"Peri Peri Corn":130,"Chilli Cheese Corn":160,"Peri Peri Cheese Corn":160,"Veg Cheese Corn":140,"Chatpata Cheese Corn":160},
            GarlicBread:{"Cheese Garlic Bread":150,"Veg Cheese Garlic Bread":180,"Cheese Corn Garlic Bread":180,"Chilli Cheese Garlic Bread":180,"Paneer Cheese Garlic Bread":200,"Jail Special Garlic Bread":230,"Butter Garlic Bread":110},
            Brownie:{"Brownie With Ice Cream":180,"Hot Chocolate Brownie":200,"Hot Oreo Brownie":220,"Sizzling Brownie":250},
            Fries:{"French Fries":110,"Masala French Fries":130,"Mix Fries":150,"Peri Peri French Fries":150,"Masala Cheese Fries":170,"Mayo Cheese Fries":170,"Peri Peri Cheese Fries":190,"Loaded Cheese Fries":230,"Cheese Fries":140},
            Rice:{"Fried Rice":180,"Manchurian Rice":200,"Singapuri Rice":200,"Schezwan Rice":200,"Paneer Rice":250,"Burnt Garlic Rice":220,"Fortune Pot Rice":250,"Veg Mongolian Rice":220,"Chilli Garlic Rice":230},
            Manchurian:{"Manchurian Dry":160,"Manchurian Gravy":160,"Schezwan Manchurian":180,"Gobhi Manchurian Dry":180,"Gobhi Manchurian Gravy":180,"Green Manchurian Dry":200,"Green Manchurian Gravy":200,"Peri Peri Manchurian":200,"Baby Corn Manchurian Dry":230,"Baby Corn Manchurian Gravy":230,"Paneer Manchurian Dry":250,"Paneer Manchurian Gravy":250,"Paneer Schezwan Dry":260,"Paneer Schezwan Gravy":260,"Paneer in Hot Garlic Dry":270,"Paneer in Hot Garlic Gravy":270,"Chilli Potato":180,"Honey Chilli Potato":200,"Veg Mexican Manchurian Dry":250,"Veg Mexican Manchurian Gravy":250,"Green Paneer Manchurian Dry":290,"Green Paneer Manchurian Gravy":290},
            Crispy:{"Exotic Veg Crispy Salt&Pepper":240,"Exotic Veg Crispy Green Pepper":240,"Exotic Veg Crispy Schezwan":240,"Crispy Corn Salt&Pepper":200,"Crispy Corn Green Pepper":200,"Crispy Corn Schezwan":200},
            Bhel:{"Chinese Bhel":160,"Bombay Bhel":180},
            Noodles:{"Hakka Noodles":180,"Singapuri Noodles":200,"Manchurian Noodles":200,"Schezwan Noodles":200,"Burnt Garlic Noodles":230,"Paneer Noodles":280,"Veg Mongo":260},
            PremiumChinese:{"Veg 65":220,"Paneer Chilli Dry":250,"Paneer Chilli Gravy":250,"Paneer 65":280},
            Soup:{"Manchow Soup":120,"Lemon Coriander Soup":120,"Noodle Soup":120,"Exotic Veg Clear Souo":120,"Sweet Corn Soup":120,"Tomato Soup":120},
            Choupsey:{"American Choupsey":150,"Chinese Choupsey":250},
            Sizzler:{"Veg Chainese Sizzler":450},
            Salad:{"Exotic Salad":150,"Paneer Salad":180,"Cheese Salad":180},
            KulchaSandwich:{"Cheese Blast Kulcha":230,"Cheese Corn Kulcha":210,"Chilli Cheese Corn Kulcha":220,"Chilli Cheese Kulcha":210,"Chilli Paneer Kulcha":210,"Masala Cheese Kulcha":190,"Paneer Loaded Kulcha":230,"Paneer Makhani Kulcha":210,"Paneer Masala":210,"Tandoori Paneer Kulcha":210,"Veg Cheese Corn Kulcha":210,"Veg Cheese Kulcha":200,"Veg Mayo Corn Kulcha":180},
            NachosChips:{"Nachos":150,"Cheesling Chips":180,"Cheese Loaded Nachos":200}
        },
        rating:"New",
        openhr:11,
        openmin:0,
        closehr:23,
        closemin:30,
        direction:"https://goo.gl/maps/uRNTfxCGFGRGeUiY7",
        cuisine:"Chinese, Italian",
        type:"Multicuisine",
        menulink:"https://drive.google.com/file/d/14MZuIBIV3VV72j_n8Ez-g8J_1rGP9Cef/view?usp=sharing",
        costavg:"600 for 2 person"
    },
    {
        id:4,
        code:788781288581,
        name:"Fannito Pizza",
        location:"Nana Varachha, Surat",
        image:"/images/FannitoPizzaVara6a/fp1.jpeg",
        image2:"/images/FannitoPizzaVara6a/fp2.jpeg",
        image3:"/images/FannitoPizzaVara6a/fp3.jpeg",
        image4:"/images/FannitoPizzaVara6a/fp4.jpeg",
        image5:"/images/FannitoPizzaVara6a/fp5.jpeg",
        image6:"/images/FannitoPizzaVara6a/fp6.jpeg",
        image7:"/images/FannitoPizzaVara6a/fp7.jpeg",
        image8:"/images/FannitoPizzaVara6a/fp8.jpeg",
        discount:"10%",
        special:"",
        contact:"7887888581",
        menu:{
            Classic:{"Margherita(Classic Mozzarella Cheese) Regular":99,"Margherita(Classic Mozzarella Cheese) Medium":199,"Margherita(Classic Mozzarella Cheese) Large":399},
            SimplyVeg:{"Double Cheese(Loaded with Extra Cheese) Regular":189,"Double Cheese(Loaded with Extra Cheese) Medium":339,"Double Cheese(Loaded with Extra Cheese) Large":539,"City Dream(Cheese,Onion,Green Chilly,Capsicum,Coriandder,Garlic) Regular":189,"City Dream(Cheese,Onion,Green Chilly,Capsicum,Coriandder,Garlic) Medium":339,"City Dream(Cheese,Onion,Green Chilly,Capsicum,Coriandder,Garlic) Large":539,"Tangy Tomato(Cheese,Sweet Corn,Capsicum,Tomato,Pineapple) Regular":189,"Tangy Tomato(Cheese,Sweet Corn,Capsicum,Tomato,Pineapple) Medium":339,"Tangy Tomato(Cheese,Sweet Corn,Capsicum,Tomato,Pineapple) Large":539,"Children Special(Cheese,Pineapple,Paneer,Black Olive) Regular":189,"Children Special(Cheese,Pineapple,Paneer,Black Olive) Medium":339,"Children Special(Cheese,Pineapple,Paneer,Black Olive) Large":539},
            Favourite:{"Paneer Chilly Pizza(Cheese,Tomato,Green Chilli,Onion,Capsicum,Chatpata Paneer) Regular":229,"Paneer Chilly Pizza(Cheese,Tomato,Green Chilli,Onion,Capsicum,Chatpata Paneer) Medium":399,"Paneer Chilly Pizza(Cheese,Tomato,Green Chilli,Onion,Capsicum,Chatpata Paneer) Large":599,"Hot Spicy Pizza(Cheese,Green Chilli,Onion,Capsicum,Red Paprika) Regular":229,"Hot Spicy Pizza(Cheese,Green Chilli,Onion,Capsicum,Red Paprika) Medium":399,"Hot Spicy Pizza(Cheese,Green Chilli,Onion,Capsicum,Red Paprika) Large":599,"Hawaiian Fantasy(Cheese,Pineapple,Jalapeno,Sweet Corn,BBQ Paneer) Regular":229,"Hawaiian Fantasy(Cheese,Pineapple,Jalapeno,Sweet Corn,BBQ Paneer) Medium":399,"Hawaiian Fantasy(Cheese,Pineapple,Jalapeno,Sweet Corn,BBQ Paneer) Large":599,"Veggie Lovers(Cheese,Mushroom,Capsicum,Onion,Black Olive,Tomato,Paneer) Regular":229,"Veggie Lovers(Cheese,Mushroom,Capsicum,Onion,Black Olive,Tomato,Paneer) Medium":399,"Veggie Lovers(Cheese,Mushroom,Capsicum,Onion,Black Olive,Tomato,Paneer) Large":599,"Deluxe Veg Pizza(Cheese,Onion,Babycorn,Capsicum,Mushroom) Regular":229,"Deluxe Veg Pizza(Cheese,Onion,Babycorn,Capsicum,Mushroom) Medium":399,"Deluxe Veg Pizza(Cheese,Onion,Babycorn,Capsicum,Mushroom) Large":599},
            Signature:{"BBQ Paneer With Spring Onion(Cheese,Spicy Sauce,Spring Onion,Onion,BabyCorn,Capsicum,Smokey Paneer) Regular":249,"BBQ Paneer With Spring Onion(Cheese,Spicy Sauce,Spring Onion,Onion,BabyCorn,Capsicum,Smokey Paneer) Medium":459,"BBQ Paneer With Spring Onion(Cheese,Spicy Sauce,Spring Onion,Onion,BabyCorn,Capsicum,Smokey Paneer) Large":699,"Mexican Pizza(Cheese,Mexican Sauce,Red Bell Pepper,Tomato,Onion,Sweet Corn,Capsicum,Black Olive) Regular":249,"Mexican Pizza(Cheese,Mexican Sauce,Red Bell Pepper,Tomato,Onion,Sweet Corn,Capsicum,Black Olive) Medium":459,"Mexican Pizza(Cheese,Mexican Sauce,Red Bell Pepper,Tomato,Onion,Sweet Corn,Capsicum,Black Olive) Large":699,"Exotica(Cheese,Red Bell Pepper,BabyCorn,Capsicum,Black Olive,Sweet Corn,Paneer) Regular":249,"Exotica(Cheese,Red Bell Pepper,BabyCorn,Capsicum,Black Olive,Sweet Corn,Paneer) Medium":459,"Exotica(Cheese,Red Bell Pepper,BabyCorn,Capsicum,Black Olive,Sweet Corn,Paneer) Large":699,"American Hit(Cheese,Capsicum,Onion,Babycorn,Jalapeno) Regular":249,"American Hit(Cheese,Capsicum,Onion,Babycorn,Jalapeno) Medium":459,"American Hit(Cheese,Capsicum,Onion,Babycorn,Jalapeno) Large":699,"Paneer Tikka(Cheese,Onion,Capsicum,Red Paprika,SweerCorn,Tomato,Cajun Spice Paneer) Regular":249,"Paneer Tikka(Cheese,Onion,Capsicum,Red Paprika,SweerCorn,Tomato,Cajun Spice Paneer) Medium":459,"Paneer Tikka(Cheese,Onion,Capsicum,Red Paprika,SweerCorn,Tomato,Cajun Spice Paneer) Large":699,"Veggie Paradise(Cheese,Onion,Capsicum,SweetCorn,Tomato,Mushroom,Tandoori Paneer) Regular":249,"Veggie Paradise(Cheese,Onion,Capsicum,SweetCorn,Tomato,Mushroom,Tandoori Paneer) Medium":459,"Veggie Paradise(Cheese,Onion,Capsicum,SweetCorn,Tomato,Mushroom,Tandoori Paneer) Large":699},
            Supreme:{"Pune Express(Cheese,Garlic,Green Chilli,Onion,Spinach,Red Paprika,Chatpata Paneer) Regular":279,"Pune Express(Cheese,Garlic,Green Chilli,Onion,Spinach,Red Paprika,Chatpata Paneer) Medium":524,"Pune Express(Cheese,Garlic,Green Chilli,Onion,Spinach,Red Paprika,Chatpata Paneer) Large":799,"Red Bell Corn Pizza(Cheese,Onion,Red Bell Pepper,Sweet Corn,BabyCorn,Mushroom) Regular":279,"Red Bell Corn Pizza(Cheese,Onion,Red Bell Pepper,Sweet Corn,BabyCorn,Mushroom) Medium":524,"Red Bell Corn Pizza(Cheese,Onion,Red Bell Pepper,Sweet Corn,BabyCorn,Mushroom) Large":799,"7 Cheese Pizza(White Mozarella,Cream White Cheese,Cheddar,Monterey Jack,Cream Orange Cheese,Colby,Orange Cheddar) Regular":279,"7 Cheese Pizza(White Mozarella,Cream White Cheese,Cheddar,Monterey Jack,Cream Orange Cheese,Colby,Orange Cheddar) Medium":524,"7 Cheese Pizza(White Mozarella,Cream White Cheese,Cheddar,Monterey Jack,Cream Orange Cheese,Colby,Orange Cheddar) Large":799,"Paneer Makhani(Cheese,Makhani Gravy,Onion,Capsicum,Red Bell Pepper,Chatpata Paneer) Regular":279,"Paneer Makhani(Cheese,Makhani Gravy,Onion,Capsicum,Red Bell Pepper,Chatpata Paneer) Medium":524,"Paneer Makhani(Cheese,Makhani Gravy,Onion,Capsicum,Red Bell Pepper,Chatpata Paneer) Large":799,"Peri Peri Paneer Pizza(Cheese,Onion,Green CHilli,Garlic,Corriander,Capsicum,Tomato,PeriPeri Paneer) Regular":279,"Peri Peri Paneer Pizza(Cheese,Onion,Green CHilli,Garlic,Corriander,Capsicum,Tomato,PeriPeri Paneer) Medium":524,"Peri Peri Paneer Pizza(Cheese,Onion,Green CHilli,Garlic,Corriander,Capsicum,Tomato,PeriPeri Paneer) Large":799,"Pasta Pizza(Cheese,Onion,Capsicum,Tomato,Tandoori Pasta) Regular":279,"Pasta Pizza(Cheese,Onion,Capsicum,Tomato,Tandoori Pasta) Medium":524,"Pasta Pizza(Cheese,Onion,Capsicum,Tomato,Tandoori Pasta) Large":799,"Fannito Special(Popular Spicy Tandoori Sauce,Cheese,Onion,Capsicum,Green Chilli,Red Paprika,Black Olives,Tandoori Paneer) Regular":279,"Fannito Special(Popular Spicy Tandoori Sauce,Cheese,Onion,Capsicum,Green Chilli,Red Paprika,Black Olives,Tandoori Paneer) Medium":524,"Fannito Special(Popular Spicy Tandoori Sauce,Cheese,Onion,Capsicum,Green Chilli,Red Paprika,Black Olives,Tandoori Paneer) Large":799},
            ExtraToppings:{},
            Combo:{"Combo For All(Simply Veg,1-Pizza Regular,2-Garlic Bread Piece,French Fries,Colddrink 200ml)":270,"Paisa Vasool Combo(Classic,Simply Veg,2-Pizza Regular,1-Colddrink 250ml)":299,"Dil Khush Combo(Classic,Simply Veg,Favourite,2-Pizza Regular,2-Classic Garlic Bread Piece)":359,"Fantastic Four Combo(1-Sweetcorn,1-Onion,1-Onion&Green Pepper,1-Paneer&Chilly Regular,Colddrink 500ml)":469,"Hunger Saviour Combo(Simply Veg,1-Pizza Large,2-Classic Garlic Bread Piece,1-Colddrink 250ml)":569,"Couple Combo(Favourite,Simply Veg,Any 2 Pizza Medium,1-colddrink 500ml)":599,"Double Special Combo(Favourite,2-Pizza Regular,French Fries,Garlic Bread,Chilli Garlic Pops,Colddrink 500ml)":629,"All Day Combo(Supreme,1-Pizza Medium,Supreme Garlic Bread,Cheese Shotz Pops,White Sauce Pasta,1-Colddrink 500ml)":689,"Party Time Combo(Classic,Simply Veg, Favourite,2-Pizza Medium,Red Sauce Pasta,Supreme Garlic Bread,1-Colddrink 500ml)":849,"Family Meal Combo(Signature,2-Pizza Large,Chilli Garlic Pops,Garlic Bread,French Fries,Cheese Shotz Pop,2-Cheese Dip,2-Cold Drink 500ml)":1389,"6 to 8 people,Signature,Supreme,2-Pizza Large,Chilli Galric Pops,Garlic Bread,French Fries,Cheese SHotz Pop,2-Cheese Dips,2-Colddrink 500ml":2083},
            SideOrder:{"Classic Garlic Bread":109,"Supreme Garlic Bread":129,"Cheese Dip":30},
            Pasta:{"White Sauce Pasta":210,"Red Sauce Pasta":210,"White Sauce Garlic Pasta":210,"Pink Sauce Pasta":210,"Pesto Pasta":210},
            Appetizer:{"Chilli Garlic Pops":120,"Cheese Shotz Pop":120,"Veggie Stick":90,"French Fries":120},
            Dessert:{"Ice Cream With Chocolate Sauce":60,"Hot Brownie With Chocolate Sauce":99,"Hot Brownie With Chocolate Sauce & Ice cream":160,"Sizzling Brownie":199},
            Mocktails:{"Mojito Mix":99,"Strawberry Mojito":129,"Watermelon Mojito":129,"Basil Mojito":129,"Mango Mojito":129,"Iced Tea":99,"Sky Blue":149,"Pinacolada":149,"Cindrella":149,"Beach Vibes":149,"Boomer":149,"Popcorn":149,"Refreshing":149,"The Perfect Sunset":149,"Cranberry":129}
        },
        rating:"New",
        openhr:9,
        openmin:30,
        closehr:23,
        closemin:0,
        direction:"https://goo.gl/maps/pziVh1vxpjwerBt46",
        cuisine:"Pizza, Fast Food, Beverages",
        type:"Pizza",
        menulink:"https://drive.google.com/file/d/1-OE92SGWb-3OmrtyEV4nxH2xYcNN_lRk/view?usp=sharing",
        costavg:"400 for 2 person"
    },
    {
        id:7,
        name:"369 Pizzaro",
        location:"Kamrej, Surat",
        image:"/images/369PizzaroKamrej/3p3.jpeg",
        image2:"/images/369PizzaroKamrej/3p2.jpeg",
        image3:"/images/369PizzaroKamrej/3p1.jpeg",
        image4:"/images/369PizzaroKamrej/3p4.jpeg",
        image5:"/images/369PizzaroKamrej/3p5.jpeg",
        image6:"/images/369PizzaroKamrej/3p6.jpeg",
        image7:"/images/369PizzaroKamrej/3p7.jpeg",
        image8:"/images/369PizzaroKamrej/3p7.jpeg",
        discount:"10%",
        special:"",
        contact:"9909031369",
        menu:{
            Simple:{"Margherita Small":135,"Margherita Medium":295,"Margherita Large":465},
            Stylish:{"Mac O Mac Small":165,"Mac O Mac Medium":355,"Mac O Mac Large":495,"Makhani Mashhoor Small":165,"Makhani Mashhoor Medium":355,"Makhani Mashhoor Large":495,"Corn Wave Small":165,"Corn Wave Medium":355,"Corn Wave Large":495,"Onion Punch Small":165,"Onion Punch Medium":355,"Onion Punch Large":495},
            Premium:{"Farm Fresh Small":205,"Farm Fresh Medium":505,"Farm Fresh Large":635,"Indian Garden Small":205,"Indian Garden Medium":505,"Indian Garden Large":635,"Hawaiian Style Small":205,"Hawaiian Style Medium":505,"Hawaiian Style Large":635,"Sweet Spicy Small":205,"Sweet Spicy Medium":505,"Sweet Spicy Large":635,"Flying Spring Small":205,"Flying Spring Medium":505,"Flying Spring Large":635,"Special Paneer Small":205,"Special Paneer Medium":505,"Special Paneer Large":635},
            Royal:{"Mexicano Small":225,"Mexicano Medium":525,"Mexicano Large":665,"Pesto Painting Small":225,"Pesto Painting Medium":525,"Pesto Painting Large":665,"Crazy Korma Small":225,"Crazy Korma Medium":525,"Crazy Korma Large":665,"Hell Boy Small":225,"Hell Boy Medium":525,"Hell Boy Large":665,"Authentic Veg Small":225,"Authentic Veg Medium":525,"Authentic Veg Large":665,"Tandoori Tadka Small":225,"Tandoori Tadka Medium":525,"Tandoori Tadka Large":665},
            Legend:{"Punjab Da Paneer Tadka Small":245,"Punjab Da Paneer Tadka Medium":550,"Punjab Da Paneer Tadka Large":695,"Schezwan Thunder Small":245,"Schezwan Thunder Medium":550,"Schezwan Thunder Large":695,"Wild Garlic Pizza Small":245,"Wild Garlic Pizza Medium":550,"Wild Garlic Pizza Large":695,"Peri Peri Pizza Small":245,"Peri Peri Pizza Medium":550,"Peri Peri Pizza Large":695,"Great Lovers Small":245,"Great Lovers Medium":550,"Great Lovers Large":695,"Mac Cheesy Small":245,"Mac Cheesy Medium":550,"Mac Cheesy Large":695,"369 Pizzaro Cottage Cheese Small":245,"369 Pizzaro Cottage Cheese Medium":550,"369 Pizzaro Cottage Cheese Large":695,"Tandoori Touch Small":245,"Tandoori Touch Medium":550,"Tandoori Touch Large":695,"Texas Treat Small":245,"Texas Treat Medium":550,"Texas Treat Large":695,"Salsa Mexicano Small":245,"Salsa Mexicano Medium":550,"Salsa Mexicano Large":695,"Hot Fantasy Small":245,"Hot Fantasy Medium":550,"Hot Fantasy Large":695,"Italian Retreat Small":245,"Italian Retreat Medium":550,"Italian Retreat Large":695,"Pesto Patakha Small":245,"Pesto Patakha Medium":550,"Pesto Patakha Large":695},
            Classic:{"Tomato & Cheese Small":69,"Onion & Cheese Small":79,"Capsicum & Cheese Small":89,"Golden Corn & Cheese Small":99,"Onion, Bell Paper & Cheese Small":115,"Onion & Paneer Small":125,"Capsicum & Paneer Small":125,"Jalapeno,Olives & Cheese Small":125,"Jalapeno,Golden Corn,Paneer & Cheese Small":139,"Red & Yellow Bell Pepper,Red Paprika,Paneer & Cheese Small":145},
            Pasta:{"Cheesy White Sauce(6pcs)":169,"Mix Sauce(6pcs)":169,"Indi Pasta(6pcs)":169,"Spicy Maxi(6pcs)":169},
            GarlicBread:{"Plain(3pcs)":79,"Cheesy(3pcs)":89,"Corn & Chilli(3pcs)":99,"Onion & Chilli(3pcs)":99,"Supreme(Sweer Corn,Onion,Jalapeno & Olives)(3pcs)":109,"Paneer Tikka(3pcs)":109},
            StuffedBreadSticks:{"5 Cheese Stuff(3pcs)":169,"Paneer Tikka Stuffed(3pcs)":169,"Schezwan Stuffed(3pcs)":169,"Stuffed Garlic(3pcs)":159,"Italian Garlic Sticks(6pcs)":125}
        },
        rating:"New",
        openhr:11,
        openmin:0,
        closehr:23,
        closemin:0,
        direction:"https://goo.gl/maps/nBvxH4XnhaNR6EQx8",
        cuisine:"Pizza, Fast Food",
        type:"Pizza",
        menulink:"https://drive.google.com/file/d/1oe9MojLgu_jLf93kNVdQZgbJKmodw9_5/view?usp=sharing",
        costavg:"400 for 2 person"
    },
    {
        id:5,
        code:851140509057,
        name:"Joker Restaurant",
        location:"Khao Gali, Kamrej",
        image:"/images/JokerKamrej/jk1.jpeg",
        image2:"/images/JokerKamrej/jk2.jpeg",
        image3:"/images/JokerKamrej/jk1.jpeg",
        image4:"/images/JokerKamrej/jk2.jpeg",
        image5:"/images/JokerKamrej/jk1.jpeg",
        image6:"/images/JokerKamrej/jk2.jpeg",
        image7:"/images/JokerKamrej/jk1.jpeg",
        image8:"/images/JokerKamrej/jk2.jpeg",
        discount:"10%",
        special:"",
        contact:"8511409057",
        menu:{
            Starter:{"Paneer Tikka Dry":180,"Paneer Malai Tikka":200,"Paneer Achari Tikka":200,"Hara Bhara Kabab":160,"Veg Sik Kabab":200},
            Soup:{"Veg Manchow Soup":100,"Hot N Sour":100,"Cream of Tomato":100},
            Chinese:{"Veg Manchurian Dry":100,"Veg Manchurian Gravy":100,"Paneer Chilly Dry":200,"Panner Chilly Gravy":200,"Paneer Manchurian Dry":180,"Paneer Manchrian Gravy":180,"Veg Hakka Noodles":120,"Manchurian Noodles":130,"Chinese Bhel":120,"Veg Fry Rice":120,"Manchurian Fry Rice":130},
            Punjabi:{"Veg Jaipuri":150,"Veg Kolhapuri":150,"Veg Hyderabadi":150,"Veg Makhhanwala":140,"Mix Vegetable":100,"Veg Handi":150,"Veg Kadai":150,"Veg Toofani":150,"Veg Angara":180,"Veg Tawa":160,"Chana Masala":100,"Mushroom Masala":170,"Plain Palak":100,"Garlic Palak":130,"Aloo Palak":100,"Dal Palak":100,"Sev Tomato":100,"Sev Bhaji":100,"Aloo Matar":100,"Jeera Aloo":100,"Sukhi Bhaji":80},
            Paneer:{"Palak Paneer":150,"Mutter Paneer":140,"Paneer Mushroom Masala":190,"Paneer Butter Masala":180,"Paneer Tikka Masala":180,"Paneer Handi":170,"Paneer Kadai":170,"Paneer Toofani":180,"Paneer Bhurji":180,"Paneer Tawa":180,"Paneer Chatpata":190,"Paneer Garlic":190,"Paneer Angara":200,"Paneer Pasanda":200,"Paneer Kaju Masala":200,"Paneer Cheese Masala":200,"Paneer Patiyala":200,"Cheese Butter Masala":210,"Paneer Mumtaaz":300,"Paneer Damdar":350,"Paneer Aflatoon":300,"Paneer E Punjab":350,"Paneer Angari":360,"Paneer Amritsari":340,"Paneer Navabi":330,"Paneer Dildar":340,"Paneer Magic":370},
            Kofta:{"Malai Kofta(Sweet)":170,"Cheese Kofta":200,"Kaju Kofta":190,"Nargisi Kofta":190,"Veg Kofta":150,"Kashmiri Kofta(Sweet)":180,"Paneer Kofta":180,"Tarang Mahal":450,"Rajwadi Kofta":300,"Trivani Kofta":400},
            Kaju:{"Kaju Curry":170,"Kaju Curry Butter":190,"Kaju Paneer":190,"Kaju Masala":190,"Kaju Fry Masala":200,"Kaju Butter Masala":190,"Kaju Paneer Masala":190,"Kaju Cheese Masala":200,"Kaju Garlic":200,"Kaju Angara":220,"Khoya Kaju(Sweet)":220,"Kaju Kamal":350,"Kaju Delight":300,"Kaju Afghani":350,"Kaju Darbari":300,"Nuts Delight":330,"Kaju Desert":370,"Panjim Point":370,"Cashew King":360,"Pride of Nuts":400},
            Dal:{"Dal Fry":90,"Dal Fry Butter":110,"Dal Tadka":110,"Dal Tadka Butter":130},
            Rice:{"Plain Rice":70,"Masala Rice":100,"Jeera Rice":90,"Veg Pulav":120,"Paneer Pulav":150,"Kaju Pulav":160,"Cheese Pulav":170,"Joker Sp. Pulav":200,"Kashmiri Pulav":200},
            Biryani:{"Veg Biryani":140,"Hyderabadi Biryani":150,"Sangam Dum Biryani":250,"Begum Dam Biryani":250,"Sp. Joker Biryani":300},
            Tandoori:{"Tandoori Roti":20,"Butter Tandoori Roti":25,"Plain Nan":40,"Butter Nan":45,"Cheese Nan":80,"Garlic Nan":55,"Chur Chur Nan":70,"Lachha Parantha":55,"Aloo Parantha":80,"Veg Parantha":100,"Methi Parantha":90,"Butter Kulcha":45,"Onion Kulcha":55,"Masala Kulcha":80,"Paneer Kulcha":90,"Cheese Kulcha":90,"Stuuf Kulcha":80},
            Roti:{"Plain Bajra Roti":25,"Butter Bajra Roti":30,"Plain Lasaniya Roti":35,"Butter Lasaniya Roti":40,"Plain Makai Roti":25,"Butter Makai Roti":30,"Plain Juvar Roti":25,"Butter Juvar Roti":30,"Plain Roti":12,"Butter Roti":15,"Parotha":30,"Thepla":20,"Butter Parotha":35,"Vagharelo Roti":100},
            Special:{"Dal Bhaat":70,"Mix Dal Bhaat":90,"Kadhi Khichadi":70,"Mala Kadhi Khichadi":90,"Dal Vatki":20,"Kadhi Vatki":20},
            Kathiyawadi:{"Sp. Green Undhiyo":100,"Sp. Ringan Bhartu":100,"Bharela Ringan":100,"Bharela Karela":100,"Bharela Marcha":100,"Sev Tomato":80,"Rajwadi Dhokali":100,"Lasaniya Bhatka":100,"Kaju Ghathiya":130,"Dahi Tikhari":100},
            Thali:{"Gujarati(2-Sabji, 5-Roti/2-Rotla, Dal Bhaat/Kadhi Khichadi, Butter Milk, Papad)":140,"Gujarati Delux(2-Sabji, 1-Kathor, 1-Farshan, 1-Sweet, 5-Roti/2-Rotla, Dal Bhaat/Kadhi Khichadi, Butter Milk, Papad)":210,"Gujarati Super Delux(2-Sabji, 1-Kathor, 1-Farshan, 1-Sweet, 7-Roti/3-Parantha, Dal Bhaat/Kadhi Khichadi, Butter Milk, Papad)":260,"Punjabi(1-Paneer Sabji, 1-Veg Sabji, 3-Butter Tandoori/5-Butter Chapati, Dal Fry, Jeera Rice, Butter Milk, Papad)":160,"Punjabi Delux(1-Paneer Sabji, 1-Veg Sabji, 1-Chana Masala, 3-Butter Tandoori/5-Butter Chapati, Dal Fry, Jeera Rice, 1-Raita, 1-Farshan, 1-Sweet, Butter Milk, Papad)":220,"Punjabi Super Delux(1-Paneer Sabji, 1-Veg Sabji, 1-Chana Masala, 5-Butter Tandoori/8-Butter Chapati, Dal Fry, Jeera Rice, 1-Raita, 1-Farshan, 1-Sweet, Butter Milk, Papad)":300},
            PavBhaji:{"Pav Bhaji":100,"Butter Pav Bhaji":120,"Cheese Butter Pav Bhaji":160,"Green Pav Bhaji":140,"Red Gatola":240,"Green Gatola":240,"Tawa Pulav":150},
            SouthIndian:{"Plain Dhosa":60,"Masala Dhosa":100,"Rava Plain Dhosa":80,"Rava Masala Dhosa":130,"Rava Onion Dhosa":80,"Rava Onion Masala Dhosa":140,"Mysore Masala Dhosa":120,"Ginny Roll":170,"RajaRani Dhosa":170,"Spring Roll Dhosa":160,"Cheese Palak Paneer Dhosa":220,"Sp. Joker Dhosa":230,"Onion Uttapam":120,"Tomato Uttapam":120,"Mix Uttapam":130,"Idli Sambhar":70,"Fry Idli":80,"Vada Sambhar":80,"Dahi Vada":100,"Veg Tomato Omlet":110,"Veg Mix Omlet":100,"Veg Onion Omlet":120}
        },
        rating:"New",
        openhr:11,
        openmin:0,
        closehr:23,
        closemin:30,
        direction:"https://goo.gl/maps/HX92F45fr4UirG92A",
        cuisine:"Gujarati, Punjabi, Kathiyawadi, Chinese",
        type:"Fine dine",
        menulink:"https://drive.google.com/file/d/1jLTJC_Q3D6XThfvm1Snekh2GPBcml4Cc/view?usp=sharing",
        costavg:"300 for 2 person"
    },
    {
        id:8,
        name:"Kake Di Hatti",
        location:"Adajan, Surat",
        image:"/images/harikrushna.jpeg",
        discount:"10%",
        rating:4.5
    },
    {
        id:12,
        name:"Royal Dine",
        location:"Kamrej, Surat",
        image:"/images/harikrushna.jpeg",
        discount:"10%",
        rating:4.4
    },
    {
        id:6,
        name:"Tapi Maiya Restaurant",
        location:"Kamrej, Surat",
        image:"/images/harikrushna.jpeg",
        discount:"10%",
        rating:4.4
    }
]
export default Hotellist;