const Hotellist=[
    {
        id:1,
        name:"Harikrushna Restaurant",
        location:"Kamrej, Surat",
        image:"/images/HarikrushnaKamrej/hk1.jpeg",
        image2:"/images/HarikrushnaKamrej/hk2.jpeg",
        image3:"/images/HarikrushnaKamrej/hk3.jpeg",
        image4:"/images/HarikrushnaKamrej/hk1.jpeg",
        image5:"/images/HarikrushnaKamrej/hk4.jpeg",
        image6:"/images/HarikrushnaKamrej/hk5.jpeg",
        image7:"/images/HarikrushnaKamrej/hk6.jpeg",
        image8:"/images/HarikrushnaKamrej/hk7.jpeg",
        discount:"10%",
        special:"Best Rated",
        contact:"9925899996",
        menu:{
            Soup:{"Tomato Soup":120,"Veg Manchow Soup":130,"Veg Hot & Sour Soup":130,"Swwet Corn Soup":135,"Lemon & Corriander Soup":145},
            Chinese:{"Manchurian Dry":160,"Manchurian Gravy":160,"Veg Hakka Noodles":160,"Schezwan Fry Rice":160,"Veg Fry Rice":160,"Manchurian Rice":160,"Special Chinese Bhel":170,"Veg Crispy":180,"Paneer Chilli Dry":210,"Paneer Chilli Gravy":210},
            Other:{"Chole Bhature":150,"Cheese Chole Bhature":180,"Paneer Chole Bhature":180,"Extra Bhature":50},
            Kathiyawadi:{"Rajwadi Undhiyu":95,"Rajwadi Dhokali":95,"Sev Tameta":90,"Potato Shak":90,"Kathol Shak":90,"Lasaniya Sev Tameta":105,"Dal(Kathiyawadi)":40,"Bhaat":40,"Kadhi(Evening)":40,"Khichdi(Evening)":40,"Vegetable Khichdi(Evening)":90,"Masala Khichdi(Evening)":90,"Palak Khichdi(Evening)":90,"Dal Khichdi":100,"Dahi Tikhari":95,"Dahi":50,"Rotla(Bajri)":28,"Tawa Parantha":28,"Swami Roti":16,"Gud":20},
            Kaju:{"Kaju Curry":230,"Kaju Paneer":250,"Kaju Masala":240,"Kaju Handi":240,"Kaju Palak Masala":240,"Kaju Butter Masala":240,"Kaju Cheese Masala":250,"Kaju Lasaniya":250,"Special Harikrushna":250},
            KathiyawadiDesiDhamal:{"Kathiyawadi Special":135,"Sp. Cheese Lilidungdi Tameta":135,"Kajughatiya Shak":130,"Kaju Patra":130,"Lilva Patra":130,"Makai Tameta":100,"Liladana Lasan Shak":130,"Jira Aloo":100,"Desi Shak Dungli Bateta":105,"Lilidungli Gathiya Shak":105,"Bharela Ringal Ditiya Shak":105,"Lili Dungli Bateta":105,"Sev Methi Shak":105,"Lila Shakbhaji Mix":105},
            Vegetable:{"Chana Masala":160,"Veg Kadhai":170,"Mix Veg":170,"Veg Hariyali":180,"Veg Kolhapuri":180,"Veg Makhanwala":180,"Veg Diwani Handi":180,"Veg Angara":200,"Veg Jaipuri":180,"Veg Cheese Tawa":210,"Veg Tawa":180,"Veg Toofani":180,"Veg Handi":180},
            Paneer:{"Chana Paneer":185,"Matar Paneer":185,"Palak Paneer":190,"Paneer Kadhai":190,"Paneer Tikka Masala":190,"Paneer Chatpata":190,"Paneer Toofani":190,"Paneer Maharaja":190,"Paneer Butter Masala":190,"Paneer Angara":190,"Paneer Diwani Handi":190,"Paneer Bhuji":210,"Paneer Mushroom Masala":210,"Junglee Paneer":210,"Paneer Lasaniya":210,"Cheese Paneer Masala":210,"Cheese Butter Masala":210,"Mushroom Masala":210,"Paneer Masala":190,"Paneer Tawa Masala":190,"Paneer Pasanda":210},
            Dal:{"Dal Fry":130,"Dal Fry Tadka":150,"Dal Hariyali":150,"Dal Kolhapuri":150},
            Rice:{"Jira Rice":110,"Veg Pulav":150,"Veg Biryani":155,"Kaju Pulav":165,"Hyderabadi Biryani":160},
            TandooriEvening:{"Plain Tandoori Roti":35,"Butter Tandoori Roti":40,"Plain Tandoori Parantha":45,"Butter Tandoori Parantha":50,"Plain Kulcha":45,"Butter Kulcha":50,"Plain Tandoori Naan":50,"Butter Tandoori Naan":60,"Cheese Naan":95,"Cheese Garlic Naan":95}
        },
        rating:"New",
        openhr:11,
        openmin:0,
        closehr:22,
        closemin:30,
        direction:"https://goo.gl/maps/Gpbin39k2gYHNJmW9",
        cuisine:"Gujarati, Punjabi, Kathiyawadi, Chinese",
        type:"Fine dine",
        menulink:`https://drive.google.com/file/d/14_4xE0BP7PEJSCjZ3RsCGnopAHZvW7aU/view?usp=drive_link`,
        costavg:"500 for 2 person"
    
    },
    {
        id:2,
        name:"The Lion King",
        location:"Kashi Plaza, Kamrej",
        image:"/images/LionKingKamrej/lk1.jpeg",
        image2:"/images/LionKingKamrej/lk2.jpeg",
        image3:"/images/LionKingKamrej/lk1.jpeg",
        image4:"/images/LionKingKamrej/lk4.jpeg",
        image5:"/images/LionKingKamrej/lk5.jpeg",
        image6:"/images/LionKingKamrej/lk6.jpeg",
        image7:"/images/LionKingKamrej/lk7.jpeg",
        image8:"/images/LionKingKamrej/lk8.jpeg",
        discount:"10%",
        special:"Premium Partner",
        contact:"9054001536",
        menu:{
            Soup:{"Veg Sweet Corn":90,"Lemon Corriander":90,"Hot & Shower":100,"Manchow":110,"Tomato":90,"Cream of Mushroom":120,"Brokly(Mix)":110,"Brant Garlic":100},
            Sizzler:{"Veg Grilled":280,"Veg Indian Coaties":320,"Chilli Paneer":300,"Mix Veg":320},
            Chinese:{"Veg Noodle":130,"Veg Hakka Noodles":130,"Chilli Garlic Noodles":140,"Veg Schezwan Noodles":140,"Honey Chilli Potato":160,"Pen Fries Noodles":140,"Spring Roll":160,"Dragon Roll":170,"Veg Kothe":150,"Veg Manchurian":140,"Crispy Corn":150,"Veg Crispy":180,"Paneer Chilli":220,"Paneer 65":230,"Paneer Nuggets":250,"Paneer Crispy":220,"American Chopsy":180,"Cheese Ball":220,"Veg Fried Rice":130,"Manchurian Fried Rice":140,"Schezwan Fried Rice":140,"Triple Schezwan Fried Rice":200,"Veg All Mix":180,"Pasta Red Sauce":140,"Pasta White Sauce":180},
            TandoorKeAngaare:{"Veg Dahi Kabab(8pcs)":150,"Veg Harabhara Kabab(8pcs)":140,"Veg Sik Kabab(8pcs)":200,"Paneer Tikka":230,"Paneer Achari Tikka":240,"Paneer Lahori Tikka":260,"Paneer Lahsuni Tikka":240,"Paneer Hariyali Tikka":250,"Paneer Pahadi Tikka":250,"Paneer Malai Tikka":260,"Mushroom Tikka":260,"Babycorn Tikka":220,"Aloo Pahadi Tikka":180,"Fancy Tandoori Platter":400},
            Raita:{"Veg Raita":70,"Boondi Raita":80,"Pineapple Raita":100,"Fruit Raita":120},
            KajuSpecial:{"Kaju Curry":240,"Kaju Masala":240,"Kaju Paneer":260,"Kaju Khoya":240,"Kaju Lasanya":240},
            KoftaKamal:{"Veg Kofta":180,"Angoori Kofta":180,"Nargis Kofta":180,"Malai Kofta White":200,"Malai Kofta Yellow":200,"Paneer Kofta":180},
            Punjabi:{"Sev Tomato":120,"Mix Veg":160,"Veg Handi":160,"Veg Kolhapuri":180,"Jeera Aloo Methi":120,"Jeera Aloo Mutter":120,"Jeera Aloo Gobi":120,"Bhindi Masala":140,"Bhindi Jodhpuri":140,"Corn Tomato Masala":150,"Corn Palak":170,"Punjabi Chole":130,"Aloo Chole":120,"Chole Paneer":180,"Veg Hyderabadi":150,"Diwani Handi":180},
            Paneer:{"Mutter Paneer":170,"Paneer Masala":170,"Palak Paneer":170,"Paneer Kadhai":200,"Paneer Lavabdar":220,"Paneer Handi":240,"Paneer Punjabi":200,"Paneer Chatpata":220,"Paneer Kolhapuri":210,"Paneer Butter Masala":250,"Shahi Paneer":260,"Paneer Lahsuniya":230,"Paneer Tikka Masala":260,"Paneer Lahori Tikka Masala":260,"Paneer Angara":260,"Paneer Toofani":250,"Paneer Dhaba":260,"Paneer Kurchan":280,"Paneer Maratha":260,"Paneer Patiyala":280},
            Rice:{"Plain Rice":100,"Jeera Rice":120,"Masala Rice":120,"Veg Pulav":140,"Kashmiri Pulav":160,"Tava Pulav":130,"Veg Biryani":140,"Veg Matka Biryani":150,"Hydrabadi Biryani":150},
            Dal:{"Dal Fry":120,"Dal Tadka":130,"Dal Makhani":140,"Dal Lahsaniya":130,"Dal Palak":120},
            Bread:{"Plain Roti":10,"Butter Roti":15,"Plain Nan":30,"Butter Nan":40,"Messi Roti":40,"Lachcha Parantha":40,"Garlic Nan":50,"Stuffed Kulcha & Parantha":60,"Aloo Parantha":60,"Onion Parantha":50,"Mix Veg Parantha":50,"Plain Parantha":50,"Cheese Nan":70,"Cheese Garlic Nan":80,"Kashmiri Nan":80,"Bread Basket(6 Type of Tandoori Roti)":160},
            Thali:{"Punjabi Thali(1 Paneer Sabji, 1 Veg Sabji, 4 Butter Roti, Dal, Rice, Papad, Salad, Raita)":150},
            Other:{"Veg Fancy Cutlet":130,"French Fry":100,"Corn Chat":100,"Chole Bhature":100,"Chole Kulche":100}
        },
        rating:"New",
        openhr:11,
        openmin:0,
        closehr:23,
        closemin:30,
        direction:"https://goo.gl/maps/hgo7CrBXepW5TJbH7",
        cuisine:"Gujarati, Punjabi, Kathiyawadi, Chinese",
        type:"Fine dine",
        menulink:"https://drive.google.com/file/d/10LTfiVv08pFMDRVlPfP7n9l1k9r5Fh82/view?usp=sharing",
        costavg:"500 for 2 person"
    },
    {
        id:3,
        name:"Dummy 1",
        location:"Kamrej, Surat",
        image:"/images/harikrushna.jpeg",
        discount:"20%",
        rating:4.1,
        menu:{
            Kaju:{"Kaju Butter":190,"Kaju Butter Masala":120},
            Paneer:{"Kadhai Paneer":170,"Paneer Punjabi":100},
            Dal:{"Dal Fry":180,"Dal Tadka":170,"Dal Makhani":170}
        },
        openhr:11,
        openmin:0,
        closehr:21,
        closemin:0,
        special:"Best Pick for You",
        contact:"70152XXXXX",
        direction:"https://goo.gl/maps/Gpbin39k2gYHNJmW9",
        cuisine:"Gujarati, Punjabi, Kathiyawadi, Chinese",
        type:"Fine dine",
        costavg:"500 for 2 person"
    },
    {
        id:4,
        name:"Dummy 2",
        location:"Kamrej, Surat",
        image:"/images/harikrushna.jpeg",
        discount:"10%",
        rating:4.3
    },
    {
        id:5,
        name:"Khao gali",
        location:"Kamrej, Surat",
        image:"/images/harikrushna.jpeg",
        discount:"10%",
        rating:3.7
    },
    {
        id:6,
        name:"Bansari",
        location:"swami k pass, Surat",
        image:"/images/harikrushna.jpeg",
        discount:"20%",
        rating:1.7
    },
    {
        id:7,
        name:"Dhyey fafda",
        location:"Dada bhagwan complex, Surat",
        image:"/images/harikrushna.jpeg",
        discount:"15%",
        rating:3.7
    }
]
export default Hotellist;